### ISSUE TITLE
Warning messages received

### ISSUE THREAD

**Issue by ewinter64** [EliGurarie/cyclomort#46]
Hi Eli

I'm pleased to have found your package cyclomort. I'm currently receiving the following warning messages when fitting the models:

> In sqrt(diag(solve(fits$hessian))) : NaNs produced
> In fit_cyclomort(x, n.seasons = n.seasons) :
>   Upper confidence limit for weights manually coerced to 1

Are you able to expand on why these have arisen?

Many thanks for your help.

Emily

**Comment by EliGurarie** [comment]
Hi Emily, 

I'm glad the package is (maybe) useful!  I'd be curious about the application. 

The message you're receiving reflects some difficulty that R's optimization algorithm (in the `optim` function) -  is having in maximizing the likelihood; or, more specifically, in obtaining the "Hessian", which is used to get confidence intervals.  Typically, the error means that whichever of the parameters ends up getting an NA in the confidence interval is genuinely hard to estimate (not enough data / not enough structure in the data), so should be interpreted as "large".  The second warning (probably unrelated to the first) just says that the "weight" parameter's estimated upper CI is greater than 1, which can happen just because of the nature of using a Hessian (a measure of how pointy the likelihood profile is at the MLE estimate) to estimate CI's.  If it's at all helpful, here's the relevant portion of a lecture covering (very cursorily) [how confidence intervals are estimated from the Hessian's when maximizing a likelihood function](https://terpconnect.umd.edu/~egurarie/teaching/Biol709/Topic3/Lecture14_Likelihoods.html#confidence_intervals:_theory).  

I wouldn't worry too much about either of these warnings, as they only affect the confidence intervals.  If you really need those confidence intervals, you can try using a different "method" in the `fit_cyclomort` function ... the methods come from the [`optim`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/optim) function will fix the warning, though that could also introduce fatal errors.  The options are: `"Nelder-Mead", "BFGS", "CG", "L-BFGS-B", "SANN", "Brent"` (default `"L-BFGS-B"`, which allows for lower and upper bounds).   A terrific link about how `optim` (a true below-the-hood workhorse in R) and the various methods work, by the way, is [here](http://www.ibm.com/developerworks/library/ba-optimR-john-nash/). 

A better fix would be for us to implement a bootstrap method, which is in some ways more reliable but much slower, to obtain confidence intervals for all the parameters.  We could but that on an eventual wishlist. 

Hope that's somewhat helpful!
- Elie

**Comment by ewinter64** [comment]
Hi Elie

Really appreciate that information. Thank you very much.

The application of my data analysis is to look at seasonal mortality in two species of freshwater fish. I’ve previously been using other survival methods and included ‘season’ as a covariate, so your new package provides an alternative perspective.

Many thanks and all the best

Emily
