### ISSUE TITLE
another CRAN review

### ISSUE THREAD

**Issue by EliGurarie** [EliGurarie/cyclomort#48]
\dontrun{} should only be used if the example really cannot be executed
(e.g. because of missing additional software, missing API keys, ...) by
the user. That's why wrapping examples in \dontrun{} adds the comment
("# Not run:") as a warning for the user.
Is this really necessary?
If not, please unwrap the examples if they are executable in < 5 sec, or
replace \dontrun{} with \donttest{}.

You write information messages to the console that cannot be easily
suppressed.
It is more R like to generate objects that can be used to extract the
information a user is interested in, and then print() that object.
Instead of print()/cat() rather use message()/warning()  or
if(verbose)cat(..) (or maybe stop()) if you really have to write text to
the console.
(except for print, summary, interactive functions)
e.g. select_seasons()

Please make sure that you do not change the user's options, par or
working directory. If you really have to do so within functions, please
ensure with an *immediate* call of on.exit() that the settings are reset
when the function is exited. e.g.:
...
oldpar <- par(no.readonly = TRUE)       # code line i
on.exit(par(oldpar))                    # code line i + 1
...
par(mfrow=c(2,2))                       # somewhere after
...
e.g.: plot_cmfit()

Please always make sure to reset to user's options(), working directory
or par() after you changed it in examples and vignettes and demos.
e.g.:
oldpar <- par(mfrow = c(1,2))
...
par(oldpar)
e.g. findDelta.Rd

Pay attention that the options should be set back when the examples are
run! So if the par(oldpar) is in \dontrun that is not enough, since it
is not run when example() is called.
e.g. censor_sycloSurv.Rd

Please fix and resubmit.

**Comment by pthompson234** [comment]
Alright, I think we are all good here! I'm going to close this for now but feel free to reopen if you notice anything. Here's a summary of what I've done (and I've noticed you appear to have done some of this already, so I'm just keeping up with your changes as well):

 - Replace any instances of \dontrun{} with \donttest{}
 - Replaced any instances of print() or cat() with message() **unless** I was inside of a print/summary function, or inside an if (print) statement, which we have for a couple of the functions
 - Included the oldpar / par thing for any cases where it was necessary (i.e., any cases where we change par inside the package). Inside functions, I used the on.exit(par(old.par)) trick, and inside examples and what not I just did it manually at the end of the script, as is done in the review here

The newest commit should be up and ready to go. It says that I haven't checked the package yet, but I have done so now and everything is OK (because there are no new changes, there's nothing new to commit).
